// <auto-generated />
namespace DummyApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class post_downvote : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(post_downvote));
        
        string IMigrationMetadata.Id
        {
            get { return "201610041445107_post_downvote"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
